### ISSUE TITLE
Global variables in functions

### ISSUE THREAD

**Issue by Ioan-Popovici** [Skatterbrainz/aztools#1]
I like this toolkit but there's gotta be a better way 😂

**Comment by Skatterbrainz** [comment]
I totally agree. It's still early. Really about 3 hours effort so far

**Comment by Skatterbrainz** [comment]
and btw - THANK YOU! That is the best comment I've read in a long time. :)   What would you suggest as an alternative to how I'm saving global values? I could write them to file or registry. That would incur some minor performance overhead, but maybe not enough to notice. Thoughts?

**Comment by Ioan-Popovici** [comment]
LoLI was just teasing you because I know you can take a joke, but if you want my opinion:

You could use Parameters and pass those with PSBoundParameters.

If the parameter is not specified, you could to ask the user to set them permanently to the registry or a json config file, or temporary for the session.

You could then initialize those once per session or on demand.

For example, I use global vars when I don't need such a complex setup by assigning them to the default value for the parameter. Then I can still pass a different value if I want to. But I would not recommend this in a module for obvious reasons. You want the cmdlets to perform predictably.

**Comment by Skatterbrainz** [comment]
Ah! Gotcha! That makes sense and I'll play around with that idea. Sorry for the slow humor> It's been a crazy week. I'm looking forward to sleeping this weekend.

**Comment by Skatterbrainz** [comment]
I'm still hoping for something more convenient than global vars, but for now I can't see a better option. I'm making sure the names are longer and unique so hopefully it doesn't conflict with anyone else's variables.
